services:
  naush-ddm:
    build:
      context: .
      dockerfile: Dockerfile
    image: xhunt3rx/naush-ddm
    container_name: naush-ddm
    tty: true
    ports:
      - 65534:22
      - 65535:3389
    volumes:
      - naush-ddm-storage:/home/naush/persist
      # Update proper content in id_rsa, id_rsa.pub, client.ovpn, credentials
      - ./mount/.ssh/id_rsa:/home/naush/.ssh/id_rsa
      - ./mount/.ssh/id_rsa.pub:/home/naush/.ssh/id_rsa.pub
      - ./mount/.ssh/config:/home/naush/.ssh/config
      - ./mount/vpn:/home/naush/vpn
      - ./mount/bashrc_custom:/home/naush/.bashrc_custom
    cap_add:
      - net_admin # for openvpn support
      - sys_admin # for sshfs support
    devices:
      - /dev/net/tun # for openvpn support
      - /dev/fuse # for sshfs support

volumes:
  naush-ddm-storage:
    name: naush-ddm-storage
