services:
  ubuntu-xrdp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu-xrdp
    container_name: ubuntu-xrdp
    tty: true
    ports:
      - 65535:3389
    # Required for OpenVPN tunnel creation
    # cap_add:
    #   - net_admin
    # devices:
    #   - /dev/net/tun
