# COMMAND: docker run -itd -e XRAY_VMESS_AEAD_FORCED=false -v $PWD/db/:/etc/x-ui/ -v /etc/letsencrypt/live/freedom.naushikha.com/:/etc/letsencrypt/live/freedom.naushikha.com/:ro -v /etc/letsencrypt/archive/freedom.naushikha.com/:/etc/letsencrypt/archive/freedom.naushikha.com/:ro --network=host --restart=unless-stopped --name 3x-ui ghcr.io/mhsanaei/3x-ui:latest
# COMPOSE: docker compose -f portainer.yml up
# https://www.composerize.com/
# https://www.decomposerize.com/

name: 3x-ui
services:
  3x-ui:
    stdin_open: true
    tty: true
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - 3x-ui:/etc/x-ui/
      - /etc/letsencrypt/live/freedom.naushikha.com/:/certs/live/freedom.naushikha.com/:ro
      - /etc/letsencrypt/archive/freedom.naushikha.com/:/certs/archive/freedom.naushikha.com/:ro
    network_mode: host
    restart: unless-stopped
    container_name: 3x-ui
    image: ghcr.io/mhsanaei/3x-ui:latest
volumes:
  3x-ui:
# POST INSTALL;
# * Default username:pwd is admin:admin
# * Setup certs using internal mount location
