name: 3x-ui
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./db/:/etc/x-ui/
    network_mode: host
    restart: unless-stopped
# POST INSTALL;
# * Default username:pwd is admin:admin
