name: drive
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: drive-filebrowser
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ./files:/srv
      - ./config/filebrowser.json:/.filebrowser.json
      - ./config/filebrowser.db:/database/filebrowser.db
    ports:
      - "55555:80"
# Run below for proper UID and GID for filebrowser user;
# touch config/filebrowser.db
# echo "UID=$(id -u)" > .env
# echo "GID=$(id -g)" >> .env
