services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/confs:/etc/nginx/confs:ro
      - ./config/nginx/auth:/etc/nginx/auth:ro
      - ./data/certbot/www:/var/www/certbot # webroot for certbot acme challenges
      - ./data/certbot/conf:/etc/letsencrypt # all certbot files stored here
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./data/certbot/www:/var/www/certbot # webroot for certbot acme challenges
      - ./data/certbot/conf:/etc/letsencrypt # all certbot files stored here
    entrypoint: >
      /bin/sh -c '
        trap "exit 0" TERM INT;
        while true; do
          certbot renew --webroot -w /var/www/certbot;
          sleep 43200 &  # 12h
          wait $!;
        done
      '
    networks:
      - webnet

networks:
  webnet:
    name: webnet
#########################################################
# Important: run content in create-certificates.sh to create certificates
